sonar.projectKey=AUY1102-Pipeline
sonar.organization=Enzo.

# Esto le dice a Sonar que analice todo el código actual
sonar.sources=.

# Exclusiones (para que no analice carpetas innecesarias)
sonar.exclusions=node_modules/**, coverage/**, dist/**

# La URL del servidor
sonar.host.url=https://sonarcloud.io