sonar.projectKey=Kuyime_AUY1102-Pipeline
sonar.organization=kuyime
sonar.sources=.
sonar.exclusions=node_modules/**, coverage/**, dist/**, **/*.test.js, **/*.spec.js
sonar.host.url=https://sonarcloud.io