name: CI/CD Pipeline - Examen Final

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # REQUISITO: Disparar en PR hacia la rama 'master'
    branches: [ "master" ]

jobs:
  # TRABAJO 1: Análisis de Seguridad y Calidad
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Importante para que Sonar lea el historial

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Si falla el nombre del proyecto o la calidad, esto se pondrá rojo ❌

  # TRABAJO 2: Build y Deploy Docker
  build-and-deploy:
    needs: security-check # REQUISITO: Interrumpir despliegue si falla seguridad
    runs-on: ubuntu-latest
    if: always() # Intenta correr para ver logs, pero 'needs' manda

    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir Imagen (Usando packs.json simulado)
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest .

      - name: Ejecutar Pruebas Unitarias (Dentro del contenedor)
        # Esto funcionará porque Docker ahora usa el json falso con el script "test"
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest npm test

      - name: Publicar Imagen
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest