name: CI/CD Pipeline con Seguridad

on:
  push:
    branches: [ "develop" ]
  pull_request:
    # REQUISITO: Ejecutar análisis en PR hacia master
    branches: [ "master" ]

jobs:
  security-and-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Importante para que Sonar analice el historial

      # REQUISITO: Integrar SonarQube (SonarCloud)
      # Si el análisis falla, el pipeline se detiene aquí.
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token por defecto de GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # El que creaste tú

  build-and-deploy:
    # REQUISITO: Interrumpir despliegue si hay problemas (needs)
    # Este trabajo NO se ejecuta si 'security-and-quality' falla.
    needs: security-and-quality
    runs-on: ubuntu-latest
    # Solo desplegamos si es un push (no en PR) o si tú decides que los PR también construyan
    if: github.event_name == 'push' 
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      # Tu truco del archivo json falso para que Docker no falle
      - name: Preparar entorno simulado
        run: cp packs.json package.json || echo "packs.json no encontrado, usando original"

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest .

      - name: Correr Pruebas Unitarias
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest npm test

      - name: Publicar en Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest