name: CI/CD Pipeline - Examen

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ] # CORREGIDO: Apuntando a master

jobs:
  # TRABAJO 1: Seguridad y Calidad (Parte 3)
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necesario para SonarCloud

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Si esto falla, el pipeline se detiene aquí (Exit code error)

  # TRABAJO 2: Build y Deploy Docker (Parte 2)
  build-and-deploy:
    needs: security-check # REQUISITO: Depende de que seguridad pase
    runs-on: ubuntu-latest
    if: always() # Intenta ejecutar para ver logs, pero 'needs' lo bloqueará si falla el anterior

    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir Imagen (Usando packs.json simulado)
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest .

      - name: Ejecutar Pruebas Unitarias
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest npm test

      - name: Publicar Imagen
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/examen-duoc:latest